### ISSUE TITLE
zsh: command not found compgen / zsh: compgen: function definition file not found

### ISSUE THREAD

**Issue by MrMineDe** [armoar334/linecomp#1]
When sourcing/running linecomp.sh i get the following error messages:

```
zsh: command not found: compgen
commands_get:1: commands: attempt to set slice of associative array
```

When adding
`autoload -U compgen` to my zshrc i get the following error messages:
```

commands_get:1: compgen: function definition file not found
commands_get:1: commands: attempt to set slice of associative array
```
This is probably easy to fix and a "mistake" on my side, but it should probably be added to the installation guide/troubleshooting guide.

( My bad 😄)

**Comment by armoar334** [comment]
This script is for bash exclusively, it will not work when run under any other shell. I have now added a check at the start to indicate this
