### ISSUE TITLE
newline on every keypress

### ISSUE THREAD

**Issue by dyipon** [armoar334/linecomp#2]
hi,

i just tried on on debian bullseye, with GNU bash 5.2.12, but after sourcing it drops a newline on every keypress:
```
$ source linecomp.sh 
x@k3s 20:06:28 ~
x@k3s 20:06:28 ~
x@k3s 20:06:28 ~
x@k3s 20:06:28 ~
x@k3s 20:06:28 ~

```

is there any idea how can I fix that?

**Comment by armoar334** [comment]
Hmm, I can't seem to recreate that myself. Is it possible you have echo or printf aliased to have any extra arguments?
Edit: also what terminal application are you using?

**Comment by dyipon** [comment]
im using Mate terminal, but you are right, something messed up my settings. I tried linecomp on a vanilla bash, and its working.

thanks!
