### ISSUE TITLE
purple fragments are not removed at enter

### ISSUE THREAD

**Issue by Vosjedev** [armoar334/linecomp#7]
The purple fragments are not removed when I press enter.
To reproduce:
do something like
```shell
echo Lorem ipsum dolor sit amet.
```
Then enter.
Then start typing this again, but press enter at
```shell
echo Lorem ipsum
```
The purple fragments of the whole thing are still there.

**Comment by armoar334** [comment]
Fixed in commit 0224b34691f4e9a16aa8c16527eef775c92bad12
